storage:
  data_dir: data

http:
  host: 0.0.0.0
  port: 8000

youtube:
  interval_seconds: 30

app:
  convert_to:
    - codec: flac
      kbps: 256
      ext: flac
    - codec: aac
      kbps: 192
      ext: m4a

security:
  enable_auth: true
  secret: change-me
  password: change-me
