storage:
  data_dir: /data

http:
  host: 0.0.0.0
  port: 8000

youtube:
  interval_seconds: 30

app:
  convert_to:
    - codec: aac
      kbps: 192
    - codec: flac
      kbps: 256

security:
  enable_auth: false
  secret: change-me
  password: change-me
