services:
  web:
    build: .
    image: mijnstroom:latest
    command: ["python", "-m", "mijnstroom.start"]
    environment:
      MIJNSTROOM_DATA_DIR: /data
    ports:
      - "8000:8000"
    volumes:
      - data:/data
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped

volumes:
  data:
